#ifndef __TASKS_CONFIG_H__
#define __TASKS_CONFIG_H__

#define CONSOLE_TASK_NAME "Console"
#define CAN_SNIFF_TASK_NAME "CanSniff"
#define WEATHER_TASK_NAME "WStation"
#define DISPLAY_TASK_NAME "Display"

#define CAN_SNIFF_TASK_PERIOD_TICKS pdMS_TO_TICKS(250)
#define WEATHER_TASK_PERIOD_TICKS pdMS_TO_TICKS(1000)
#define CONSOLE_TASK_PERIOD_TICKS pdMS_TO_TICKS(2000)
#define DISPLAY_TASK_PERIOD_TICKS pdMS_TO_TICKS(1000)
#define STATUS_LED_TIMER_PERIOD_TICKS pdMS_TO_TICKS(500)
#define CLI_TASK_SERIAL_POLL_PERIOD_TICKS pdMS_TO_TICKS(25)

#define CONSOLE_TASK_PRIORITY (tskIDLE_PRIORITY + 2)
#define DISPLAY_TASK_PRIORITY (tskIDLE_PRIORITY + 1)
#define WEATHER_TASK_PRIORITY (tskIDLE_PRIORITY + 1)
#define CAN_SNIFF_TASK_PRIORITY (tskIDLE_PRIORITY + 3)

#define CONSOLE_TASK_STACK_SIZE 256
#define CAN_SNIFF_STACK_SIZE 256
#define WEATHER_STACK_SIZE 256
#define DISPLAY_STACK_SIZE 256

#define CAN_QUEUE_LENGTH 10

#endif // __TASKS_CONFIG_H__
